################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
ASM_UPPER_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
application \
application/shell \
mbed/frameworks/mbed-client-randlib/source \
mbed/frameworks/mbed-coap/source \
mbed/frameworks/nanostack-libservice/source/IPv6_fcf_lib \
mbed/frameworks/nanostack-libservice/source/libBits \
mbed/frameworks/nanostack-libservice/source/libList \
mbed/frameworks/nanostack-libservice/source/libip6string \
mbed/frameworks/nanostack-libservice/source/nsdynmemLIB \
mbed/frameworks/nanostack-libservice/source/nsdynmemtracker \
mbed/mbed-trace \
mbed/mbednanostack2tirtos/nanostack/nanostack-hal-mbed-cmsis-rtos \
mbed/mbednanostack2tirtos/platform \
mbed/mbedtls/platform/COMPONENT_PSA_SRV_IMPL \
mbed/mbedtls/src \
mbed/mbedtls2tirtos/mbedtls/mbed-crypto \
mbed/mbedtls2tirtos/platform \
mbed/nanostack/coap-service/source \
mbed/nanostack/mbed-mesh-api/source \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ND \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN \
mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws \
mbed/nanostack/sal-stack-nanostack/source/BorderRouter \
mbed/nanostack/sal-stack-nanostack/source/Common_Protocols \
mbed/nanostack/sal-stack-nanostack/source/Core \
mbed/nanostack/sal-stack-nanostack/source/DHCPv6_Server \
mbed/nanostack/sal-stack-nanostack/source/DHCPv6_client \
mbed/nanostack/sal-stack-nanostack/source/MAC \
mbed/nanostack/sal-stack-nanostack/source/MLE \
mbed/nanostack/sal-stack-nanostack/source/MPL \
mbed/nanostack/sal-stack-nanostack/source/NWK_INTERFACE \
mbed/nanostack/sal-stack-nanostack/source/RPL \
mbed/nanostack/sal-stack-nanostack/source/Security/Common \
mbed/nanostack/sal-stack-nanostack/source/Security/PANA \
mbed/nanostack/sal-stack-nanostack/source/Security/TLS \
mbed/nanostack/sal-stack-nanostack/source/Security/eapol \
mbed/nanostack/sal-stack-nanostack/source/Security/kmp \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols \
mbed/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib/mbedOS \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/SHA256_Lib \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/etx \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/fhss \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/hmac \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11 \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/random_early_detection \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/utils \
mbed/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard \
mbed/nanostack/sal-stack-nanostack/source/ipv6_stack \
mbed/nanostack/sal-stack-nanostack/source/libDHCPv6 \
mbed/nanostack/sal-stack-nanostack/source/libNET/src \
mbed/nanostack/sal-stack-nanostack-eventloop/source \
mbed/ti-nv-driver \
mbed/ti-rf-driver/source \
software_stack/ti15_4mac \
software_stack/ti15_4mac/mac_settings \
software_stack/ti15_4mac/osal_port \
software_stack/ti15_4mac/radio_configuration \
software_stack/ti15_4mac/stack_user_api/api_mac \
sysconfig \
wisun_ncp/platform \
wisun_ncp/src/core/api \
wisun_ncp/src/core/common \
wisun_ncp/src/lib/hdlc \
wisun_ncp/src/lib/spinel \
wisun_ncp/src/ncp \

